#!/bin/bash -e
# This is a disabled hook example.
#
# To enable, make it executable:
#
#     chmod +x /etc/tklbam3/hooks.d/example-post-restore

# hooks are always called with two arguments
op=$1
state=$2

if [[ "$state" == "post" ]] && [[ "$op" == "restore" ]]; then

    echo "HOOK $0 :: op=$op state=$state pwd=$(pwd) :: "

    # run some commands here...
    # e.g. restart services, load data dumps, etc

fi
